### ISSUE TITLE
运行generateConfig.py出错

### ISSUE THREAD

**Issue by wzxyisme** [opq-osc/OPQ-SetuBot#48]
请问是我那个配置文件填错了吗？python版本是3.8.2
> wzxy@localhost:~/OPQBot/python/SetuBot/script$ python3 generateConfig.py 
Traceback (most recent call last):
  File "generateConfig.py", line 12, in <module>
    botConf = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 20 (char 115)

**Comment by yuban10703** [comment]
看看botoy.json

**Comment by wzxyisme** [comment]
看了一下配置文件socks的链接填到http那里去了，不好意思打扰了
