### ISSUE TITLE
搜图报错

### ISSUE THREAD

**Issue by IcyFeather233** [opq-osc/OPQ-SetuBot#54]
发送 搜图+图片
后台输出
```
12-10 18:59:03 INFO   GroupMsg ->  {'FromGroupId': 183319180, 'FromGroupName': '陈孟卓个人专用群', 'FromUserId': 1278263215, 'FromNickName': '陈孟卓', 'Content': '{"Content":"搜图","GroupPic":[{"FileId":2152069071,"FileMd5":"DwgbdG4fucrM6sK7FJXWyg==","FileSize":10507,"ForwordBuf":"Eip7MEYwODFCNzQtNkUxRi1COUNBLUNDRUEtQzJCQjE0OTVENkNBfS5qcGciACoEAAAAADJcFTYgOTJrQTFDODA0NWY3Y2ZlNGMxNTEyYSAgICAgIDUwICAgICAgICAgICAgICAgIHswRjA4MUI3NC02RTFGLUI5Q0EtQ0NFQS1DMkJCMTQ5NUQ2Q0F9LmpwZ0E4z++XgghAqqKFpg5IUFBDWgBgAWoQDwgbdG4fucrM6sK7FJXWynJcL2djaGF0cGljX25ldy8xMjc4MjYzMjE1LzIxNzMzMTkxODAtMjE1MjA2OTA3MS0wRjA4MUI3NDZFMUZCOUNBQ0NFQUMyQkIxNDk1RDZDQS8xOTg/dGVybT0yNTWCAVovZ2NoYXRwaWNfbmV3LzEyNzgyNjMyMTUvMjE3MzMxOTE4MC0yMTUyMDY5MDcxLTBGMDgxQjc0NkUxRkI5Q0FDQ0VBQzJCQjE0OTVENkNBLzA/dGVybT0yNTWgAekHsAHLAbgBzgLIAYtS2AF44AHGAfoBXC9nY2hhdHBpY19uZXcvMTI3ODI2MzIxNS8yMTczMzE5MTgwLTIxNTIwNjkwNzEtMEYwODFCNzQ2RTFGQjlDQUNDRUFDMkJCMTQ5NUQ2Q0EvNDAwP3Rlcm09MjU1gALLAYgCzgI=","ForwordField":8,"Url":"http://gchat.qpic.cn/gchatpic_new/1278263215/183319180-2534335053-0F081B746E1FB9CACCEAC2BB1495D6CA/0?vuin=2054479045\\u0026term=255\\u0026pictype=0"}],"Tips":"[群图片]"}', 'MsgType': 'PicMsg', 'MsgTime': 1639133943, 'MsgSeq': 885, 'MsgRandom': 3447525475, 'RedBaginfo': None}
❌ 12-10 18:59:04 ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/botoy/async_client.py", line 40, in _context_distributor
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/dist-packages/botoy/async_decorators/_ignore_botself.py", line 16, in inner
    return await func(ctx)
  File "/usr/local/lib/python3.9/dist-packages/botoy/async_decorators/_these_msgtypes.py", line 13, in inner
    return await func(ctx)
  File "/usr/local/lib/python3.9/dist-packages/botoy/async_decorators/_in_content.py", line 21, in inner
    return await func(ctx)
  File "/root/OPQ-SetuBot/plugins/bot_Search_Picture/__init__.py", line 13, in main
    await SearchPic(ctx).main()
  File "/root/OPQ-SetuBot/plugins/bot_Search_Picture/searchPicture.py", line 94, in main
    msg = self.buildmsg(res["results"][0])
KeyError: 'results'

```
bot不发消息

**Comment by IcyFeather233** [comment]
哦哦，是的，不小心多了个空格
