### ISSUE TITLE
获取freshtoken时出错

### ISSUE THREAD

**Issue by thunderaka** [opq-osc/OPQ-SetuBot#57]
其实是这样的，我没有使用其他代理上外网而是耍了小聪明使用了nginx反代理登录P站，在桌面使用火狐可以实现一秒打开pixiv并且登录但是终端运行docker之后却一直出错，不知道哪里出问题了
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 149, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 58, in func_loginh
    res = g.login(headless=True, user=ns.username, pass_=ns.password)
  File "/usr/local/lib/python3.10/site-packages/gppt/selenium.py", line 73, in login
    self.driver.get(f"{LOGIN_URL}?{urlencode(login_params)}")
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=97.0.4692.71)
Stacktrace:
#0 0x56446b15da23 <unknown>
#1 0x56446ac28e18 <unknown>
#2 0x56446ac231e6 <unknown>
#3 0x56446ac14fc6 <unknown>
#4 0x56446ac15eea <unknown>
#5 0x56446ac15292 <unknown>
#6 0x56446ac147b2 <unknown>
#7 0x56446ac135e3 <unknown>
#8 0x56446ac13933 <unknown>
#9 0x56446ac2a7da <unknown>
#10 0x56446ac903ef <unknown>
#11 0x56446ac7c992 <unknown>
#12 0x56446ac8fc5b <unknown>
#13 0x56446ac7c883 <unknown>
#14 0x56446ac523fa <unknown>
#15 0x56446ac534c5 <unknown>
#16 0x56446b18d16d <unknown>
#17 0x56446b1a35bb <unknown>
#18 0x56446b18ee75 <unknown>
#19 0x56446b1a3e85 <unknown>
#20 0x56446b18286f <unknown>
#21 0x56446b1beae8 <unknown>
#22 0x56446b1bec68 <unknown>
#23 0x56446b1d9aad <unknown>
#24 0x7fa82bf0cfa3 <unknown>

**Comment by yuban10703** [comment]
阿哲,老老实实配代理吧,没搞过反代...

**Comment by thunderaka** [comment]
啊这，那好吧，我试试另开一个虚拟机搞代理试试
