### ISSUE TITLE
这是为啥啊

### ISSUE THREAD

**Issue by 773281810** [opq-osc/OPQ-SetuBot#61]
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 149, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 58, in func_loginh
    res = g.login(headless=True, user=ns.username, pass_=ns.password)
  File "/usr/local/lib/python3.10/site-packages/gppt/selenium.py", line 73, in login
    self.driver.get(f"{LOGIN_URL}?{urlencode(login_params)}")
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=97.0.4692.71)
Stacktrace:
#0 0x559ef3f11a23 <unknown>
#1 0x559ef39dce18 <unknown>
#2 0x559ef39d71e6 <unknown>
#3 0x559ef39c8fc6 <unknown>
#4 0x559ef39c9eea <unknown>
#5 0x559ef39c9292 <unknown>
#6 0x559ef39c87b2 <unknown>
#7 0x559ef39c75e3 <unknown>
#8 0x559ef39c7933 <unknown>
#9 0x559ef39de7da <unknown>
#10 0x559ef3a443ef <unknown>
#11 0x559ef3a30992 <unknown>
#12 0x559ef3a43c5b <unknown>
#13 0x559ef3a30883 <unknown>
#14 0x559ef3a063fa <unknown>
#15 0x559ef3a074c5 <unknown>
#16 0x559ef3f4116d <unknown>
#17 0x559ef3f575bb <unknown>
#18 0x559ef3f42e75 <unknown>
#19 0x559ef3f57e85 <unknown>
#20 0x559ef3f3686f <unknown>
#21 0x559ef3f72ae8 <unknown>
#22 0x559ef3f72c68 <unknown>
#23 0x559ef3f8daad <unknown>
#24 0x7f46f5059fa3 <unknown>

**Comment by yuban10703** [comment]
我猜你机子不能上外网

**Comment by 773281810** [comment]
> 我猜你机子不能上外网

用的腾讯云服务器咋办

**Comment by yuban10703** [comment]
这个就只能你自己解决了..

**Comment by 773281810** [comment]
噢，那这个issue怎么删掉
