### ISSUE TITLE
请问refresh token的功能现在还能用吗？

### ISSUE THREAD

**Issue by Magicicesea** [opq-osc/OPQ-SetuBot#70]
我这边提示timeout，不知道是不是pixiv改了。用户和密码试过自己的都会提示同样错误。
命令是在aws的linux 实例上run的。
```
sudo docker run --rm -it eggplanter/gppt lh -u 114514 -p 1919810
Traceback (most recent call last):
  File "/usr/local/bin/gppt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 149, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/gppt/main.py", line 58, in func_loginh
    res = g.login(headless=True, user=ns.username, pass_=ns.password)
  File "/usr/local/lib/python3.10/site-packages/gppt/selenium.py", line 74, in login
    WebDriverWait(self.driver, 10).until(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559b75a78a23 <unknown>
#1 0x559b75543e18 <unknown>
#2 0x559b7557a151 <unknown>
#3 0x559b7557a311 <unknown>
#4 0x559b755acec4 <unknown>
#5 0x559b755979bd <unknown>
#6 0x559b755aac5b <unknown>
#7 0x559b75597883 <unknown>
#8 0x559b7556d3fa <unknown>
#9 0x559b7556e4c5 <unknown>
#10 0x559b75aa816d <unknown>
#11 0x559b75abe5bb <unknown>
#12 0x559b75aa9e75 <unknown>
#13 0x559b75abee85 <unknown>
#14 0x559b75a9d86f <unknown>
#15 0x559b75ad9ae8 <unknown>
#16 0x559b75ad9c68 <unknown>
#17 0x559b75af4aad <unknown>
```

**Comment by yuban10703** [comment]
https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
试试这个
或者自己手动抓包吧....

**Comment by a7236723** [comment]
解决了吗？教教我。

**Comment by eggplants** [comment]
> 解决了吗？教教我。

+1

**Comment by a7236723** [comment]
> > 解决了吗？教教我。
> 
> +1

解决了，参考这篇文章https://blog.maddestroyer.xyz/rsshub/  获取 Pixiv Refresh Token  
工具https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362
